### ISSUE TITLE
primary key of table accounts_bak overflow

### ISSUE THREAD

**Issue by xrdavies** [XDagger/openxdagpool-scripts#2]
Description:
the primary key of table accounts_bak is overflow when reach max value 2147483647.

**Comment by kbs1** [comment]
Hi Frozen, yes, that is the max value, but since the table now only stores "minedblocks", not all accounts as in previous versions, I don't think it will overflow soon. Did it overflow for you?

Regards :)

**Comment by xrdavies** [comment]
Hi kbs1, some guy reported overflow with his pool.
![img_8392](https://user-images.githubusercontent.com/1884084/48176987-8f3e1e80-e34d-11e8-86db-aa1b6e7c0c53.PNG)

**Comment by kbs1** [comment]
Hi, interesting, does he use XDAG < 0.2.5? For such versions, accounts are really saved. For >= 0.2.5, only "minedblocks" are saved as "accounts". Therefore there should be no overflow. Please tell him to execute:
```
ALTER TABLE `accounts` CHANGE `id` `id` bigint NOT NULL AUTO_INCREMENT FIRST;
```
I've also pushed new DB schema to the repo. Note: when he has only one pool wallet for all-time existence of his pool, he can simply "start fresh" by issuing `php core.php blocks startFresh`. This will truncate the table, subsequent blocks operations will import all his accounts again (without the overflow this time). It is preferable to use >= 0.2.5 as the table will contain much fewer entries (minedblocks only), which will greatly increase performance overall.

**Comment by xrdavies** [comment]
@kbs1  Thank you so much!
